spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: asdqwe123
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        temp: use_jdbc_metadata_defaults
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
